version: '3'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://sinhaarnabh888:Arnabh@cluster0.rixkb92.mongodb.net/PaymentGateway
      - JWT_SECRET=asfjgaskfgaskfgaskfgasfk
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
